service: myserverlessproject3

provider:
  name: aws
  runtime: nodejs14.x
  profile: serverless-admin
  region: eu-west-1
  environment:
    tableName: ${self:custom.tableName}
    bucketName: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
        - ses:*
      Resource: "*"

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

package:
  individually: true

custom:
  # currentStage: ${opt:stage, self:provider.stage}
  # uri:
  #   dev: http://dev.com/{proxy}
  #   qa: http://qa.com/{proxy}
  #   prod: https://prod.com/{proxy}

  tableName: player-points-table
  bucketName: demo-bucket-1
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
  serverless-offline:
    # httpsProtocol: "dev-certs"
    resourceRoutes: true
    port: 4000
    stageVariables:
      foo: "bar"

functions:
  - ${file(./infra/functions/authorizers.yml)}
  - ${file(./infra/functions/endpoints.yml)}

resources:
  # - ${file(./infra/resources/s3-bucket.yml)}
  - ${file(./infra/resources/dynamodb-tables.yml)}
  # - ${file(./infra/resources/proxy.yml)}
